name: rows_lint
description: Lint rules for dart used by projects @ Rows
version: 0.1.0
repository: https://github.com/rows/rows_lint
issue_tracker: https://github.com/rows/rows_lint/issues
homepage: https://github.com/rows/rows_lint


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  effective_dart: ^1.3.1

